# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MusicCrawler' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MusicCrawler
	pod 'SwiftSoup'
	pod 'SDWebImage'
  target 'MusicCrawlerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MusicCrawlerUITests' do
    # Pods for testing
  end

end
